# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [303]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [304]:
# your code here
print(np.__version__)

1.22.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [305]:
# Method 1
np.random.rand(2,3,5)

array([[[0.22850655, 0.58223849, 0.94021465, 0.15315298, 0.95240698],
        [0.19719548, 0.37682704, 0.95481038, 0.81856602, 0.43465752],
        [0.14990337, 0.60132665, 0.8626925 , 0.71662244, 0.06519321]],

       [[0.65836976, 0.6421217 , 0.49484473, 0.08245081, 0.63200814],
        [0.55603816, 0.17370424, 0.19858061, 0.42062356, 0.70144894],
        [0.34592944, 0.38338166, 0.79087038, 0.1143608 , 0.87796639]]])

In [306]:
# Method 2
np.random.randint(6, size=(2, 3, 5))

array([[[0, 0, 4, 2, 2],
        [0, 3, 0, 0, 5],
        [4, 4, 2, 2, 0]],

       [[3, 1, 3, 4, 4],
        [5, 4, 5, 0, 3],
        [0, 4, 3, 1, 0]]])

In [307]:
# Method 3
np.random.random_sample((2, 3, 5))

array([[[0.78287377, 0.33863388, 0.11082761, 0.11561001, 0.68733839],
        [0.52061195, 0.28749284, 0.04013829, 0.55611471, 0.56248396],
        [0.79594177, 0.57996988, 0.14756982, 0.44692831, 0.71725848]],

       [[0.24595107, 0.19430949, 0.86525623, 0.38978867, 0.74773941],
        [0.17405108, 0.4652078 , 0.98487477, 0.82297298, 0.61843855],
        [0.24657769, 0.62217102, 0.57345115, 0.11544295, 0.44509159]]])

#### 4. Print *a*.


In [308]:
# your code here
a = np.random.randint(60, size=(2, 3, 5))
print(a)

[[[21 17 38 23 49]
  [27 39 19 27 28]
  [37 31 56 42 40]]

 [[36 39 16 56 37]
  [38 17 48 42 22]
  [40 16 22 49 11]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [140]:
# your code here
b = np.random.randint(1, size=(5, 2, 3))
b.fill(1)

#### 6. Print *b*.


In [309]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [310]:
# your code here
# Yes a and b have the same size:
print(" size of a:", b.size)
print(" size of b:", a.size)

 size of a: 30
 size of b: 30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [311]:
# your answer here
#No, because they don't have the same shape

print(b.shape)
print(a.shape)


(5, 2, 3)
(2, 3, 5)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [312]:
# your code here
c = b.transpose()
c = c.reshape(2, 3, 5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [373]:
# your code/answer here
# we had to use reshape to have the same shape...
d = np.add(a, c)
d

array([[[22, 18, 39, 24, 50],
        [28, 40, 20, 28, 29],
        [38, 32, 57, 43, 41]],

       [[37, 40, 17, 57, 38],
        [39, 18, 49, 43, 23],
        [41, 17, 23, 50, 12]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [374]:
# your code/answer here
print("matrix a:", a)
print("------------------------------------")
print("matrix d:", d)

matrix a: [[[21 17 38 23 49]
  [27 39 19 27 28]
  [37 31 56 42 40]]

 [[36 39 16 56 37]
  [38 17 48 42 22]
  [40 16 22 49 11]]]
------------------------------------
matrix d: [[[22 18 39 24 50]
  [28 40 20 28 29]
  [38 32 57 43 41]]

 [[37 40 17 57 38]
  [39 18 49 43 23]
  [41 17 23 50 12]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [315]:
# your code here
e = np.multiply(a, c)
e

array([[[21, 17, 38, 23, 49],
        [27, 39, 19, 27, 28],
        [37, 31, 56, 42, 40]],

       [[36, 39, 16, 56, 37],
        [38, 17, 48, 42, 22],
        [40, 16, 22, 49, 11]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [316]:
# your code/answer here
# yes they are equal because we are multiplying by 1 every element, so it should be the same result
print(a)
print("----------------------------")
print(e)


[[[21 17 38 23 49]
  [27 39 19 27 28]
  [37 31 56 42 40]]

 [[36 39 16 56 37]
  [38 17 48 42 22]
  [40 16 22 49 11]]]
----------------------------
[[[21 17 38 23 49]
  [27 39 19 27 28]
  [37 31 56 42 40]]

 [[36 39 16 56 37]
  [38 17 48 42 22]
  [40 16 22 49 11]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [375]:
# your code here
d_max = np.max(d)
print("maximum of d", d_max)
d_min = np.min(d)
print("minimum of d", d_min)
d_mean = np.mean(d)
print("mean of d", d_mean.round(2))


maximum of d 57
minimum of d 12
mean of d 33.77


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [417]:
# your code here
f = np.empty([2,3,5], dtype=str)
f.shape
f

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [413]:
# your code here
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x, y, z] > d_min and d[x, y, z] < d_mean:
                f[x, y, z] = 25
            if d[x, y, z] > d_mean and d[x, y, z] < d_max:
                f[x, y, z] = 75 
            if d[x, y, z] == d_mean:
                f[x, y, z] = 50
            if d[x, y, z] == d_min:
                f[x, y, z] = 0
            if d[x, y, z] == d_max:
                f[x, y, z] = 100

In [414]:
f

array([[[ 25,  25,  75,  25,  75],
        [ 25,  75,  25,  25,  25],
        [ 75,  25, 100,  75,  75]],

       [[ 75,  75,  25, 100,  75],
        [ 75,  25,  75,  75,  25],
        [ 75,  25,  25,  75,   0]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [415]:
# your code here
print(d)
print("---------------------------------")
print(f)


[[[22 18 39 24 50]
  [28 40 20 28 29]
  [38 32 57 43 41]]

 [[37 40 17 57 38]
  [39 18 49 43 23]
  [41 17 23 50 12]]]
---------------------------------
[[[ 25  25  75  25  75]
  [ 25  75  25  25  25]
  [ 75  25 100  75  75]]

 [[ 75  75  25 100  75]
  [ 75  25  75  75  25]
  [ 75  25  25  75   0]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [418]:
# your code here
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x, y, z] > d_min and d[x, y, z] < d_mean:
                f[x, y, z] = "A"
            if d[x, y, z] > d_mean and d[x, y, z] < d_max:
                f[x, y, z] = "B" 
            if d[x, y, z] == d_mean:
                f[x, y, z] = "C"
            if d[x, y, z] == d_min:
                f[x, y, z] = "D"
            if d[x, y, z] == d_max:
                f[x, y, z] = "E"
f

array([[['A', 'A', 'B', 'A', 'B'],
        ['A', 'B', 'A', 'A', 'A'],
        ['B', 'A', 'E', 'B', 'B']],

       [['B', 'B', 'A', 'E', 'B'],
        ['B', 'A', 'B', 'B', 'A'],
        ['B', 'A', 'A', 'B', 'D']]], dtype='<U1')